---
- name: Configure MongoDB Database Server
  hosts: db
  become: true
  tasks:

    - name: Install dependencies
      apt:
        name:
          - gnupg
          - curl
        state: present
        update_cache: yes

    - name: Add MongoDB GPG key
      apt_key:
        url: https://www.mongodb.org/static/pgp/server-7.0.asc
        state: present

    - name: Add MongoDB APT repository
      apt_repository:
        repo: deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/7.0 multiverse
        state: present
        filename: mongodb-org-7.0

    - name: Install MongoDB
      apt:
        name: mongodb-org
        state: present
        update_cache: yes

    - name: Configure MongoDB to listen on all interfaces inside VPC
      lineinfile:
        path: /etc/mongod.conf
        regexp: '^\s*bindIp:'
        line: '  bindIp: 0.0.0.0'

    - name: Start and enable MongoDB service
      systemd:
        name: mongod
        state: restarted
        enabled: yes